global:
  scrape_interval: "15s"
  
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-jmx-exporter:9999']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']